# CONFIGURACION DEL SERVIDOR
server.port=8080

# CONEXION A LA BASE DE DATOS (POSTGRESQL)
# Reemplaza los valores con tu Connection String de Neon.tech o local
spring.datasource.url=jdbc:postgresql://tu-host-de-neon.tech/neondb?sslmode=require
spring.datasource.username=tu-usuario
spring.datasource.password=tu-contraseña
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACION DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACION DE SERIALIZACION JSON
spring.jackson.serialization.indent_output=true